# {{- $fullName := include "kongtest.fullname" . -}}
# apiVersion: configuration.konghq.com/v1
# kind: KongIngress
# metadata:
#   name: {{ $fullName }}
#   labels:
#     app: {{ template "kongtest.name" . }}
#     chart: {{ template "kongtest.chart" . }}
#     release: {{ .Release.Name }}
#     heritage: {{ .Release.Service }}
# upstream:
#   hash_on: none
#   hash_fallback: none
#   healthchecks:
#     active:
#       concurrency: 10
#       healthy:
#         http_statuses:
#         - 200
#         - 302
#         interval: 0
#         successes: 0
#       http_path: "/"
#       timeout: 1
#       unhealthy:
#         http_failures: 0
#         http_statuses:
#         - 429
#         interval: 0
#         tcp_failures: 0
#         timeouts: 0
#     passive:
#       healthy:
#         http_statuses:
#         - 200
#         successes: 0
#       unhealthy:
#         http_failures: 0
#         http_statuses:
#         - 429
#         - 503
#         tcp_failures: 0
#         timeouts: 0
#     slots: 10
# proxy:
#   protocol: http
#   path: /
#   connect_timeout: 10000
#   retries: 10
#   read_timeout: 10000
#   write_timeout: 10000
# route:
#   methods:
#   - POST
#   - GET
#   regex_priority: 0
#   strip_path: false
#   preserve_host: true
#   protocols:
#   - http
#   - https

---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rl-by-ip
config:
  hour: 100
  limit_by: ip
  second: 1
plugin: rate-limiting

# ---
# apiVersion: configuration.konghq.com/v1
# kind: KongPlugin
# metadata:
#   name: terminate-request-all
# config:
#   status_code: 403
#   message: "So Long and thankyou for the fish"
# plugin: request-termination

# ---
# apiVersion: configuration.konghq.com/v1
# kind: KongPlugin
# metadata:
#   name: restrict-by-ip
# config:
#   blacklist: 52.64.34.48
# plugin: ip-restriction

